### PR TITLE
HID-2126 Password reset form and 2FA activation

### PR DESCRIPTION
**Pull request by left23**
Branched from https://github.com/UN-OCHA/hid_api/pull/159

1. Currently placeholder markup only for both Password reset form, and 2FA tab
2. TOTP conditional based on vue app, but missing the "Activation Steps. TBD

Screenshot from 2020-11-03 16-46-03

Screenshot from 2020-11-03 16-46-11

Screenshot from 2020-11-03 16-49-00

### CODE REVIEW

**Comment by left23** [comment]
@rupl This is ready for review, with placeholder markup. 
I've added some placeholder JS, from the vue app, partly to preserve the logic. I can remove non-functional JS if you prefer, since it's in the other repo.

**Comment by rupl** [comment]
I imagine we'll use the JS and the API to accomplish this instead of totally reinventing the wheel. Thanks for the starter and we'll get it functional once we have time.

**Comment by left23** [comment]
@rupl Is this lack of functionality blocking merging this to dev?

**Comment by rupl** [comment]
Maybe we can comment out any tab that isn't functional yet? I understand the need to not keep a bazillion parallel branches open, but we also don't want to provide a confusing UX by presenting buttons and tabs that do nothing.

**Comment by left23** [comment]
@rupl This branch has only the Authorised App list tab now. Everything else is commented out.

**Comment by left23** [comment]
Merging to dev.

**Pull request merged**
