### PR TITLE
[OPS-7801] add cracklib and why not, use the base image from ECR.

### PR DESCRIPTION
**Pull request by teodorescuserban**

### CODE REVIEW

**Comment by teodorescuserban** [comment]
travis is failing because you need for travis:
- python3 and python3-dev
- cracklib-dev
- build-base (at least gcc, make and automake, but each OS has a different meta package that includes the most common things used to compile packages).

**Comment by rupl** [comment]
@teodorescuserban is this assigned to me to install the packages you listed? I'm uncertain what action I should take to make Travis pass. 

- python3 and python3-dev
- cracklib-dev
- build-base

**Comment by teodorescuserban** [comment]
well, @rupl, no, I'll take care of it.

**Comment by teodorescuserban** [comment]
there you go, @rupl 😄

**Pull request merged**
