### PR TITLE
HID-2206: dependency updates

### PR DESCRIPTION
**Pull request by rupl**
# HID-2206

More dependency updates! Run `npm install` before testing.

Two actions serve as a good test:

- Log in and edit your profile. That tests all of our DB functionality (schema reads, DB read/write)
- Use the forgot-password form to send yourself an email via mailhog. If the email looks right, the templates are working.

### CODE REVIEW

**Comment by left23** [comment]
@rupl 
I am running `npm install` in hid_api:
```
left@lucy /var/www/html/hid/hid_api (hid-2206-security-updates $=) $ node -v
v12.21.0
left@lucy /var/www/html/hid/hid_api (hid-2206-security-updates $=) $ npm i

> @newrelic/native-metrics@4.1.0 install /var/www/html/hid/hid_api/node_modules/@newrelic/native-metrics
> node ./lib/pre-build.js install native_metrics

============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> /usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
> /usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build -j 4 native_metrics
make: Entering directory '/var/www/html/hid/hid_api/node_modules/@newrelic/native-metrics/build'
  CXX(target) Release/obj.target/native_metrics/src/native_metrics.o
  CXX(target) Release/obj.target/native_metrics/src/GCBinder.o
  CXX(target) Release/obj.target/native_metrics/src/LoopChecker.o
  CXX(target) Release/obj.target/native_metrics/src/RUsageMeter.o
  SOLINK_MODULE(target) Release/obj.target/native_metrics.node
  COPY Release/native_metrics.node
make: Leaving directory '/var/www/html/hid/hid_api/node_modules/@newrelic/native-metrics/build'
install successful: _newrelic_native_metrics-4_1_0-native_metrics-72-linux-x64

> nodemon@2.0.2 postinstall /var/www/html/hid/hid_api/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 724 packages from 545 contributors and audited 730 packages in 148.718s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
but when I follow with `docker-compose up` in `hid/hid-stack` I get:
```
api_1      | [nodemon] 2.0.2
api_1      | [nodemon] to restart at any time, enter `rs`
api_1      | [nodemon] watching dir(s): *.*
api_1      | [nodemon] watching extensions: html,css,js,ejs
api_1      | [nodemon] starting `node ./server.js`
api_1      | /srv/www/node_modules/@hapi/hapi/node_modules/@hapi/teamwork/lib/index.js:8
api_1      |     #meetings = null;
api_1      |     ^
api_1      | 
api_1      | SyntaxError: Invalid or unexpected token
api_1      |     at new Script (vm.js:79:7)
api_1      |     at createScript (vm.js:251:10)
api_1      |     at Object.runInThisContext (vm.js:303:10)
api_1      |     at Module._compile (internal/modules/cjs/loader.js:657:28)
api_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
api_1      |     at Module.load (internal/modules/cjs/loader.js:599:32)
api_1      |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
api_1      |     at Module.require (internal/modules/cjs/loader.js:637:17)
api_1      |     at require (internal/modules/cjs/helpers.js:22:18)
api_1      |     at Object.<anonymous> (/srv/www/node_modules/@hapi/hapi/lib/server.js:6:18)
api_1      |     at Module._compile (internal/modules/cjs/loader.js:689:30)
api_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
api_1      |     at Module.load (internal/modules/cjs/loader.js:599:32)
api_1      |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
api_1      | [nodemon] app crashed - waiting for file changes before starting...
```

This seems to be related to a node version. Am I doing something incorrectly?

**Comment by rupl** [comment]
Whoops, I wasn't specific enough. If you go to `....../hid/hid-stack/env/local`

then you can run:

```
docker-compose exec api npm i
```

and it will do it in the container

**Review by left23 — APPROVED** [review]
Approving. I am able to login as usual and the mailhog emails are working and display as expected.

**Comment by rupl** [comment]
woohoo! thanks 🎉

**Pull request merged**
