### PR TITLE
HID-2147: frontend pipeline

### PR DESCRIPTION
**Pull request by rupl**
# HID-2147 / HID-2119 / OPS-7176

This branch reorganizes the frontend files and has some lite docs to define a workflow for styling individual pages. I took a chunk of your work in #161 and implemented it here. If I left out something major, we can ticket and return individually.

As is customary for this work, there is stuff you might consider scope creep. However in this case I was trying to rid us of cruft found while shuffling things around: bootstrap classes, layout inconsistencies, updates to make the new stack work smoothly, and small UX problems that I didn't want to ticket and return to later.

Happy to talk over this on a call, and also help you get set up on the new stack which I think will reduce some testing headaches.

## Testing

I'm looking for your input on the docs, and also general QA like:

- Can I still register (need to make a temp change in API to get around ReCAPTCHA)
- Can I reset a password?
- Can I login?

### CODE REVIEW

**Comment by rupl** [comment]
@left23 ready for a final review. Our convo yesterday served as the majority of it, but if I missed any follow-ups please call them out. Ideally I'd like to close both this PR and #161.

**Comment by left23** [comment]
@rupl Looks good to me. I've tweaked a few things that I think are uncontroversial but feel free to reverse or improve as you see fit.

1. I noticed there is no width restriction to the form elements yet - did you have specific plans for this?
2. The OCHA services button font size should be 14px. The cd-button component makes it 16px - I've added the font-size to the existing `.ocha-dropdown__see-all` rule for now, and I think I should set this in the cd.css in the common_design to avoid this issue in the future
3. The /register and /password buttons needed the cd-button classes added - I've removed `btn-primary` and replaced with classes matching those on main login form button. *There may be other forms and submit buttons that need similar treatment, depending on desired styles.
4. I added some colour rules from https://github.com/UN-OCHA/hid_api/pull/161/files#diff-1671da1302cd5c094dd762e76e142d8c1caf8f276eb884b86ef1630507e81ed2 so the H1, h2 and links are HID brand colours (as before)

I think it's ok to close #161 now. Everything of import seems to be included in this branch now.

**Review by left23 — APPROVED** [review]

**Comment by left23** [comment]
I'm able to login and reset passwords as usual. I had issues registering a new account `There was a problem validating your registration. Please try again.` but I get the impression from the PR description that is expected.

**Comment by left23** [comment]
@rupl One more thing - I'm not sure the font Exo made it into the latest styles. I can't see a Fonts directory anymore so maybe this is intentional.
It was part of main.css which is gone now https://github.com/UN-OCHA/hid_api/pull/170/files#diff-b15932692c619f9a334ecb156ac167557c3af214a8a3df8990c09232ac8a5baaL66

**Comment by rupl** [comment]
@left regarding my comment about reCAPTCHA, you can comment out the validation and return `true` so that registrations finish with success: https://github.com/UN-OCHA/hid_api/blob/dev/api/controllers/ViewController.js#L184

**Comment by rupl** [comment]
@left23 as for Exo, I searched once more and couldn't find it being referenced in our CSS files. Did I miss a reference? I did intend to remove it completely.

**Comment by left23** [comment]
> @left23 as for Exo, I searched once more and couldn't find it being referenced in our CSS files. Did I miss a reference? I did intend to remove it completely.

Nope, it's gone. I just wanted to double check that was the intention. Thorough :)

**Comment by left23** [comment]
@rupl I've confirmed registration works too.

**Comment by rupl** [comment]
Nice! Then let's give this a try on dev.

**Pull request merged**
