### PR TITLE
HID-1828: have Travis lint the codebase

### PR DESCRIPTION
**Pull request by rupl**
# HID-1828

It is past time.

### CODE REVIEW

**Comment by rupl** [comment]
yay, it's green! I have been doing functional testing as I linted, but will do one more thorough pass without ever changing code before asking for review.

**Comment by rupl** [comment]
@left23 if you can run the E2E on your local machine that should suffice for testing this.

**Review by left23 — APPROVED** [review]
Tests are green, Approving.
```
 PASS  _tests/e2e/OCHADropdown.test.js
 PASS  _tests/e2e/Login.test.js (6.142 s)
 PASS  _tests/e2e/PasswordReset.test.js (10.518 s)

Test Suites: 3 passed, 3 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        11.002 s
```

**Comment by rupl** [comment]
yay!

**Pull request merged**
